version: 2
updates:
  # Go dependencies
  - package-ecosystem: "gomod"
    directory: "/services/verifier"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    reviewers:
      - "cachet-team"
    assignees:
      - "cachet-team"

  - package-ecosystem: "gomod"
    directory: "/services/registry"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "gomod"
    directory: "/services/receipts-log"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "gomod"
    directory: "/services/issuance-gateway"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"

  # Gradle dependencies (Android)
  - package-ecosystem: "gradle"
    directory: "/mobile"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/services/verifier"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(docker)"

  - package-ecosystem: "docker"
    directory: "/services/registry"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(docker)"

  - package-ecosystem: "docker"
    directory: "/services/receipts-log"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(docker)"

  - package-ecosystem: "docker"
    directory: "/services/issuance-gateway"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(docker)"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(ci)"
