[project]
name = "cachet"
revision = "1.0"

[profiles.default]
CACHET_DB_URL = { description = "PostgreSQL database connection URL", required = true }
CACHET_JWT_SECRET = { description = "JWT signing secret key", required = true }

# Veriff Integration
VERIFF_API_KEY = { description = "Veriff API key for SDK initialization", required = true }
VERIFF_BASE_URL = { description = "Veriff API base URL", required = false, default = "https://stationapi.veriff.com" }
VERIFF_WEBHOOK_SECRET = { description = "Veriff master signature key for webhook verification", required = true }
VERIFF_WEBHOOK_BASE_URL = { description = "Base URL where Veriff should send webhooks", required = false, default = "http://localhost:8082" }

[profiles.ci]
# CI/CD Infrastructure secrets for deployment consistency
GCP_SA_KEY = { description = "Base64-encoded GCP service account key for deployment", required = true }
CACHIX_AUTH_TOKEN = { description = "Cachix authentication token for Nix caching", required = true }