[project]
name = "cachet"
revision = "1.0"

[profiles.default]
CACHET_DB_URL = { description = "PostgreSQL database connection URL", required = true }
CACHET_JWT_SECRET = { description = "JWT signing secret key", required = true }