package id.cachet.wallet.integration

import id.cachet.wallet.network.CredentialRequest
import id.cachet.wallet.network.RelaySession
import id.cachet.wallet.network.VerificationSession
import id.cachet.wallet.network.VerifyResponseDTO
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * Cross-language contract tests.
 *
 * These tests deserialize JSON generated by the Go backend (via TestGenerateContractJSON)
 * to verify that Kotlin DTOs match the Go struct serialization. If a Go field is renamed,
 * made nullable, or changes type, these tests break.
 *
 * Run with: cd mobile && ./gradlew :shared:allTests
 *
 * The golden JSON files live in testdata/contracts/ and are committed to git.
 * They are generated by: cd services/verifier && go test -run TestGenerateContract
 */
class ContractTest {

    private val json = Json {
        ignoreUnknownKeys = true
        isLenient = true
    }

    // ── VerifyResponse contracts ──

    @Test
    fun `VerifyResponse - cachet granted - all fields present`() {
        val input = VERIFY_RESPONSE_GRANTED
        val resp = json.decodeFromString<VerifyResponseDTO>(input)

        assertEquals("Childcare-Ready (ES)", resp.cachet, "field is 'cachet' not 'badge'")
        assertEquals("ok", resp.freshness)

        // predicates is a list of satisfied predicate IDs
        assertNotNull(resp.predicates, "predicates should not be null when present")
        assertEquals(2, resp.predicates!!.size)
        assertTrue(resp.predicates!!.contains("age.ge.18"))
        assertTrue(resp.predicates!!.contains("identity.verified"))

        // predicateResults
        assertEquals(3, resp.predicateResults.size)
        val ageResult = resp.predicateResults.first { it.predicateId == "age.ge.18" }
        assertEquals("satisfied", ageResult.status)
        assertNull(ageResult.reason)

        val criminalResult = resp.predicateResults.first { it.predicateId == "criminal.clear.es" }
        assertEquals("no_credential", criminalResult.status)
        assertNotNull(criminalResult.reason)

        // summary
        assertNotNull(resp.summary)
        assertTrue(resp.summary!!.cachetGranted)
        assertEquals(2, resp.summary!!.requiredSatisfied)
        assertEquals(2, resp.summary!!.requiredTotal)
    }

    @Test
    fun `VerifyResponse - no cachet - null predicates`() {
        val input = VERIFY_RESPONSE_NO_CACHET
        val resp = json.decodeFromString<VerifyResponseDTO>(input)

        assertEquals("", resp.cachet, "empty cachet when not granted")

        // This is the critical test: Go returns "predicates": null
        // Kotlin must accept this without crashing
        assertNull(resp.predicates, "null predicates from Go must deserialize as null")

        assertFalse(resp.summary!!.cachetGranted)
        assertEquals(1, resp.summary!!.requiredSatisfied)
        assertEquals(3, resp.summary!!.requiredTotal)
    }

    @Test
    fun `VerifyResponse - empty results`() {
        val input = VERIFY_RESPONSE_EMPTY
        val resp = json.decodeFromString<VerifyResponseDTO>(input)

        assertEquals("", resp.cachet)
        assertNull(resp.predicates)
        assertEquals(0, resp.predicateResults.size)
        assertFalse(resp.summary!!.cachetGranted)
    }

    // ── VerificationSession contracts ──

    @Test
    fun `VerificationSession - with ephemeral key and request object`() {
        val input = VERIFICATION_SESSION
        val sess = json.decodeFromString<VerificationSession>(input)

        assertEquals("test-session-123", sess.sessionId)
        assertEquals("dGVzdC1ub25jZQ", sess.nonce)
        assertEquals("did:web:verifier.cachet.id", sess.verifierDid)
        assertNotNull(sess.ephemeralPubKey, "ephemeralPubKey must be deserialized")
        assertEquals("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", sess.ephemeralPubKey)
        assertNotNull(sess.requestObject, "requestObject must be deserialized")
        assertTrue(sess.requestObject!!.startsWith("eyJ"), "requestObject is a JWT")
    }

    @Test
    fun `VerificationSession - without ephemeral key (backward compat)`() {
        val input = VERIFICATION_SESSION_NO_EPHEMERAL
        val sess = json.decodeFromString<VerificationSession>(input)

        assertEquals("old-session-456", sess.sessionId)
        assertNotNull(sess.nonce)
        assertNull(sess.ephemeralPubKey, "missing ephemeralPubKey should be null")
    }

    // ── Webhook payload contract ──

    @Test
    fun `Webhook payload uses camelCase field names`() {
        // This test validates the JSON shape the Go backend expects.
        // MockVeriffService must produce JSON with these exact field names.
        val input = WEBHOOK_PAYLOAD
        val obj = json.parseToJsonElement(input).jsonObject

        assertEquals("approved", obj["status"]!!.jsonPrimitive.content)

        val person = obj["person"]!!.jsonObject
        assertTrue(person.containsKey("firstName"), "must be camelCase: firstName not first_name")
        assertTrue(person.containsKey("lastName"), "must be camelCase: lastName not last_name")
        assertTrue(person.containsKey("dateOfBirth"), "must be camelCase: dateOfBirth not date_of_birth")
        assertEquals("1995-06-15", person["dateOfBirth"]!!.jsonPrimitive.content)

        val verification = obj["verification"]!!.jsonObject
        assertTrue(verification.containsKey("livenessScore"), "must be camelCase: livenessScore")
        assertTrue(verification.containsKey("overallConfidence"), "must be camelCase: overallConfidence")
        assertTrue(verification.containsKey("riskScore"), "must be camelCase: riskScore")
    }

    // ── Credential request contract ──

    @Test
    fun `Credential request proof jwk is nested object not string`() {
        val input = CREDENTIAL_REQUEST_WITH_PROOF
        val obj = json.parseToJsonElement(input).jsonObject

        assertEquals("vc+sd-jwt", obj["format"]!!.jsonPrimitive.content)

        // The proof.jwk must be a JSON object, not a string
        val proof = obj["proof"]!!.jsonObject
        val jwk = proof["jwk"]!!.jsonObject  // This would throw if jwk is a string
        assertEquals("EC", jwk["kty"]!!.jsonPrimitive.content)
        assertEquals("P-256", jwk["crv"]!!.jsonPrimitive.content)
        assertNotNull(jwk["x"])
        assertNotNull(jwk["y"])

        // Also verify we can deserialize CredentialRequest
        val req = json.decodeFromString<CredentialRequest>(input)
        assertNotNull(req.proof, "proof field must deserialize")
        val proofJwk = req.proof!!["jwk"]!!.jsonObject
        assertEquals("EC", proofJwk["kty"]!!.jsonPrimitive.content)
    }

    // ── Relay session contract ──

    @Test
    fun `RelaySession deserializes correctly`() {
        val input = RELAY_SESSION
        val sess = json.decodeFromString<RelaySession>(input)

        assertEquals("relay-session-abc", sess.sessionId)
        assertEquals("/sessions/relay-session-abc/request", sess.requestUri)
        assertEquals("/sessions/relay-session-abc/response", sess.responseUri)
    }

    // ── Golden JSON payloads (generated by Go TestGenerateContractJSON) ──
    // These are inlined from testdata/contracts/ for multiplatform compatibility.
    // If the Go side changes, regenerate with:
    //   cd services/verifier && go test -run TestGenerateContract
    // Then update these constants.

    companion object {
        val VERIFY_RESPONSE_GRANTED = """
        {
          "cachet": "Childcare-Ready (ES)",
          "freshness": "ok",
          "predicateResults": [
            {"predicateId": "age.ge.18", "status": "satisfied"},
            {"predicateId": "identity.verified", "status": "satisfied"},
            {"predicateId": "criminal.clear.es", "reason": "no credential from an accepted issuer", "status": "no_credential"}
          ],
          "predicates": ["age.ge.18", "identity.verified"],
          "summary": {"cachetGranted": true, "requiredSatisfied": 2, "requiredTotal": 2, "optionalSatisfied": 0, "optionalTotal": 1}
        }
        """.trimIndent()

        val VERIFY_RESPONSE_NO_CACHET = """
        {
          "cachet": "",
          "freshness": "ok",
          "predicateResults": [
            {"predicateId": "age.ge.18", "reason": "expected >= 18, got 0", "status": "failed"},
            {"predicateId": "identity.verified", "status": "satisfied"},
            {"predicateId": "criminal.clear.es", "reason": "no credential from an accepted issuer", "status": "no_credential"}
          ],
          "predicates": null,
          "summary": {"cachetGranted": false, "requiredSatisfied": 1, "requiredTotal": 3}
        }
        """.trimIndent()

        val VERIFY_RESPONSE_EMPTY = """
        {
          "cachet": "",
          "freshness": "ok",
          "predicateResults": [],
          "predicates": null,
          "summary": {"cachetGranted": false, "requiredSatisfied": 0, "requiredTotal": 0}
        }
        """.trimIndent()

        val VERIFICATION_SESSION = """
        {
          "sessionId": "test-session-123",
          "nonce": "dGVzdC1ub25jZQ",
          "verifierDid": "did:web:verifier.cachet.id",
          "ephemeralPubKey": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
          "requestObject": "eyJhbGciOiJFUzI1NiIsImtpZCI6ImRpZDp3ZWI6dmVyaWZpZXIuY2FjaGV0LmlkI2tleS0xIiwidHlwIjoib2F1dGgtYXV0aHotcmVxK2p3dCJ9.eyJjbGllbnRfaWQiOiJkaWQ6d2ViOnZlcmlmaWVyLmNhY2hldC5pZCJ9.fake-sig"
        }
        """.trimIndent()

        val VERIFICATION_SESSION_NO_EPHEMERAL = """
        {
          "sessionId": "old-session-456",
          "nonce": "b2xkLW5vbmNl",
          "verifierDid": "did:web:verifier.cachet.id"
        }
        """.trimIndent()

        val WEBHOOK_PAYLOAD = """
        {
          "session_id": "veriff-session-789",
          "status": "approved",
          "person": {"firstName": "Jane", "lastName": "Doe", "dateOfBirth": "1995-06-15", "confidence": 0.96},
          "document": {"number": "AB1234567", "type": "PASSPORT", "country": "EE", "authenticity": 0.97},
          "verification": {"livenessScore": 0.93, "overallConfidence": 0.96, "riskScore": 0.03, "timestamp": "2026-04-05T00:00:00Z"}
        }
        """.trimIndent()

        val CREDENTIAL_REQUEST_WITH_PROOF = """
        {
          "format": "vc+sd-jwt",
          "types": ["VerifiableCredential", "IdentityCredential"],
          "proof": {"jwk": {"kty": "EC", "crv": "P-256", "x": "test-x-coordinate", "y": "test-y-coordinate"}}
        }
        """.trimIndent()

        val RELAY_SESSION = """
        {
          "sessionId": "relay-session-abc",
          "requestUri": "/sessions/relay-session-abc/request",
          "responseUri": "/sessions/relay-session-abc/response"
        }
        """.trimIndent()
    }
}
