#!/usr/bin/env bash
set -euo pipefail

echo "Running tests with coverage..."
mkdir -p coverage
cd services/verifier && go test -coverprofile=../../coverage/verifier.out -covermode=atomic ./...
cd ../registry && go test -coverprofile=../../coverage/registry.out -covermode=atomic ./...
cd ../receipts-log && go test -coverprofile=../../coverage/receipts.out -covermode=atomic ./...
cd ../issuance-gateway && go test -coverprofile=../../coverage/issuance.out -covermode=atomic ./...
echo "Coverage reports generated in coverage/"
