openapi: 3.0.3
info:
  title: Verifier
  version: 0.1.0
paths:
  /packs:
    get:
      responses:
        '200': {description: ok}
  /presentations/verify:
    post:
      responses:
        '200': {description: ok}
